node: "hoeren.txt"          # 原始节点文件
target: "v2ray"            # 输出格式，Xray/V2Ray
insert: false              # 不插入延迟
emoji: false               # 不显示国旗
group: ""                  #不要分组
rules: []                  #不需要规则集
enabled: false
overwrite_original_rules: true
update_ruleset_on_request: false
out: "work/finale.txt"     # 输出文件路径
